name: Daily Commit Workflow

on:
  schedule:
    - cron: '30 5 * * *'  # runs daily at 05:30 UTC
  workflow_dispatch:       # allows manual trigger too

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Push changes using PAT
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "24f1001758@ds.study.iitm.ac.in"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
          git add daily-log.txt
          git commit -m "Automated daily commit"
          git push
