name: Daily Commit

on:
  schedule:
    - cron: '20 6 * * *'  # runs daily at 6:20 UTC

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: 24f1001758@ds.study.iitm.ac.in – Make daily log
        run: |
          echo "Run date: $(date)" >> daily-log.txt

      - name: Push commit using PAT
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "24f1001758@ds.study.iitm.ac.in"
          git add daily-log.txt
          git commit -m "Automated daily commit"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
          git push

